### ISSUE TITLE
Solved: No permission to access pad

### ISSUE THREAD

**Issue by oliver-s-k** [moodlehu/moodle-mod_etherpadlite#72]
Hello,

this issue is no longer a problem for me, but maybe the solution might help someone who encounters a similar problem. None of the solutions I found regarding this error message were helpful, so I traced the error through the code. It turns out that Etherpad couldn't read the session cookie because it was undefined. The cookies appeared to be the same on both Moodle and Etherpad when inspected in the developer tools. Even moving Etherpad to the Moodle server so it has the same domain or performing a fresh install were a viable solution.

What didn't stand out to me initially, but is quite obvious once you know it, is that the cookies were set as HttpOnly, preventing Node.js from accessing them. During the Moodle upgrade, I also wanted to increase security, so I set HttpOnly on Apache.

A better solution is to keep these settings away from the webserver and instead use the settings provided by Moodle. This way, all cookies from Moodle will have the HttpOnly flag, but the ones set by mod_etherpadlite will not have that flag and can be read by Node.js.

Adios
Oliver

**Comment by slaudel** [comment]
@oliver-s-k I think I'm having the same problem as you described here. I tried to debug step by step the session creation for mod_etherpad and everything looks fine, but in the end the created session is not being accessed by etherpadlite. The developer tools shows the mod_etherpad-etherpadlite session cookie as "http_only". **If this is really the issue, how do I circumvent this?**

Etherpad lite is running on its own virtual machine and hostname/domain as moodle is running on a separate vm but both do share a common domain. The set cookie should be available to both as the screenshots show.

I tried setting the cookie from mod_etherpad as http_only by tweaking the code but this didn't change anything:
```
$cookie_options = [
                'expires' => $validuntil,
                'path' => '/',
                'domain' => $this->config->cookiedomain, // leading dot for compatibility or use subdomain
                'secure' => $ssl, // or false
                'httponly' => false, // or false
                'samesite' => 'None' // None || Lax || Strict
                ];

            setcookie('sessionID', $session->sessionID, $cookie_options);
```

<img width="1868" alt="Image" src="https://github.com/user-attachments/assets/36a3dbec-be30-40d9-8626-d0bbbb1bd5d7" />
<img width="1868" alt="Image" src="https://github.com/user-attachments/assets/3a99b942-c5b6-41e2-a2da-f4ebffb003fa" />

Here comes the etherpad lite debug log to verify the session is created correctly:
```
Session Creation:
<snip>
[2025-05-19T08:05:33.339] [DEBUG] ueberDB - GET    - group:g.JmqpSL5VKwGTroKw - {"pads":{"g.JmqpSL5VKwGTroKw$stage4":1},"mappings":{}} - from database
[2025-05-19T08:05:33.340] [DEBUG] ueberDB - GET    - globalAuthor:a.uvdSKBAkFltVI0uN - {"colorId":54,"name":"Sven Laudel","timestamp":1747634733174} - from cache
[2025-05-19T08:05:33.340] [DEBUG] ueberDB - SET    - session:s.6aa987b940566e3cf925927a8ecb0279 - {"groupID":"g.JmqpSL5VKwGTroKw","authorID":"a.uvdSKBAkFltVI0uN","validUntil":1747645533} - to buffer
[2025-05-19T08:05:33.420] [DEBUG] ueberDB - SETSUB - group2sessions:g.JmqpSL5VKwGTroKw["sessionIDs","s.6aa987b940566e3cf925927a8ecb0279"] - 1
[2025-05-19T08:05:33.421] [DEBUG] ueberDB - SETSUB - author2sessions:a.uvdSKBAkFltVI0uN["sessionIDs","s.6aa987b940566e3cf925927a8ecb0279"] - 1
[2025-05-19T08:05:33.422] [DEBUG] ueberDB - GET    - group2sessions:g.JmqpSL5VKwGTroKw - {"sessionIDs":{"s.77899876f41da5d4bad09401fe444679":1,"s.76a18351f8e77da51de5ebd5a6a006c5":1,"s.362cd9fa480b1aed674faedd87c794e5":1,"s.57947ac5257dbb258fa6d5e56015aa6a":1,"s.28c92915fbfdfb749625d1c3cb99f948":1,"s.3acc97c1b7bccc9faad8e40d7d9f14c1":1,"s.858f88dce113c52a8a4a0253e44dcda6":1,"s.9d3553625495d2e086384ea859e1f500":1,"s.22f94f69f22d36c5be132c156ace7102":1,"s.4f5b5d3715c1e4ffed2981d260a4f485":1,"s.1772f692525f9c329bc6df00b9b4d8aa":1,"s.97eb594011dee4a87f4b060e86e47336":1,"s.e81da065a5d296f702bdf6c54038841f":1,"s.b24206c880b1407db5f2c61bd3601c2c":1,"s.8f82e135cc7142330cad3c400dcee0af":1,"s.8c2129faa7708a50781beb8187e5bdcc":1,"s.26aff1239249a6c952c561917815623f":1,"s.7a697510af3699409999d886f67c1786":1,"s.99da93f134ebe207cb21f9638dfdd8ee":1,"s.ab8b85353a2ef9629b99029c2513d7ea":1}} - from database
[2025-05-19T08:05:33.422] [DEBUG] ueberDB - SET    - group2sessions:g.JmqpSL5VKwGTroKw - {"sessionIDs":{"s.77899876f41da5d4bad09401fe444679":1,"s.76a18351f8e77da51de5ebd5a6a006c5":1,"s.362cd9fa480b1aed674faedd87c794e5":1,"s.57947ac5257dbb258fa6d5e56015aa6a":1,"s.28c92915fbfdfb749625d1c3cb99f948":1,"s.3acc97c1b7bccc9faad8e40d7d9f14c1":1,"s.858f88dce113c52a8a4a0253e44dcda6":1,"s.9d3553625495d2e086384ea859e1f500":1,"s.22f94f69f22d36c5be132c156ace7102":1,"s.4f5b5d3715c1e4ffed2981d260a4f485":1,"s.1772f692525f9c329bc6df00b9b4d8aa":1,"s.97eb594011dee4a87f4b060e86e47336":1,"s.e81da065a5d296f702bdf6c54038841f":1,"s.b24206c880b1407db5f2c61bd3601c2c":1,"s.8f82e135cc7142330cad3c400dcee0af":1,"s.8c2129faa7708a50781beb8187e5bdcc":1,"s.26aff1239249a6c952c561917815623f":1,"s.7a697510af3699409999d886f67c1786":1,"s.99da93f134ebe207cb21f9638dfdd8ee":1,"s.ab8b85353a2ef9629b99029c2513d7ea":1,"s.6aa987b940566e3cf925927a8ecb0279":1}} - to buffer
[2025-05-19T08:05:33.422] [DEBUG] ueberDB - GET    - author2sessions:a.uvdSKBAkFltVI0uN - {"sessionIDs":{"s.e81da065a5d296f702bdf6c54038841f":1,"s.b24206c880b1407db5f2c61bd3601c2c":1,"s.8f82e135cc7142330cad3c400dcee0af":1,"s.8c2129faa7708a50781beb8187e5bdcc":1,"s.26aff1239249a6c952c561917815623f":1}} - from database
[2025-05-19T08:05:33.423] [DEBUG] ueberDB - SET    - author2sessions:a.uvdSKBAkFltVI0uN - {"sessionIDs":{"s.e81da065a5d296f702bdf6c54038841f":1,"s.b24206c880b1407db5f2c61bd3601c2c":1,"s.8f82e135cc7142330cad3c400dcee0af":1,"s.8c2129faa7708a50781beb8187e5bdcc":1,"s.26aff1239249a6c952c561917815623f":1,"s.6aa987b940566e3cf925927a8ecb0279":1}} - to buffer
[2025-05-19T08:05:33.523] [DEBUG] API - RESPONSE, createSession, {"code":0,"message":"ok","data":{"sessionID":"s.6aa987b940566e3cf925927a8ecb0279"}}

<snip>
Accessing Session:
[2025-05-19T08:05:36.413] [DEBUG] SessionStore - SET 0cqvOojw0m3nzvIuaOe0A_jvPQHgAmqR
[2025-05-19T08:05:36.413] [DEBUG] socket.io - W27ktXnGu0_6OP1SAAAB connected from IP 172.22.26.156
[2025-05-19T08:05:36.414] [DEBUG] ueberDB - SET    - sessionstorage:0cqvOojw0m3nzvIuaOe0A_jvPQHgAmqR - {"cookie":{"originalMaxAge":864000000,"expires":"2025-05-29T06:05:36.412Z","secure":false,"httpOnly":true,"path":"/","sameSite":"Strict"},"connections":null} - to buffer
[2025-05-19T08:05:36.449] [DEBUG] socket.io - from W27ktXnGu0_6OP1SAAAB: {
  component: 'pad',
  type: 'CLIENT_READY',
  padId: 'g.JmqpSL5VKwGTroKw$stage4',
  token: 't.Qlx16bLUn3BRoWQMALzZ',
  userInfo: { colorId: null, name: null }
}
[2025-05-19T08:05:36.452] [DEBUG] ueberDB - GET    - pad:g.JmqpSL5VKwGTroKw$stage4 - {"atext":{"text":"\n","attribs":"|1+1"},"pool":{"numToAttrib":{},"nextNum":0},"head":0,"chatHead":-1,"publicStatus":false,"savedRevisions":[]} - from cache
[2025-05-19T08:05:36.453] [DEBUG] SessionStore - TOUCH 0cqvOojw0m3nzvIuaOe0A_jvPQHgAmqR
[2025-05-19T08:05:36.455] [DEBUG] ueberDB - GET    - pad2readonly:g.JmqpSL5VKwGTroKw$stage4 - "r.a5a372173fc8c73df9b433fe60a39475" - from database
[2025-05-19T08:05:36.456] [DEBUG] ueberDB - GET    - pad:g.JmqpSL5VKwGTroKw$stage4 - {"atext":{"text":"\n","attribs":"|1+1"},"pool":{"numToAttrib":{},"nextNum":0},"head":0,"chatHead":-1,"publicStatus":false,"savedRevisions":[]} - from cache
[2025-05-19T08:05:36.456] [DEBUG] auth - access denied: HTTP API session is required
[2025-05-19T08:05:36.464] [ERROR] socket.io - Error handling pad message from W27ktXnGu0_6OP1SAAAB: Error: access denied
    at Object.exports.handleMessage (/opt/etherpad/etherpad-lite/src/node/handler/PadMessageHandler.ts:320:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/opt/etherpad/etherpad-lite/src/node/handler/SocketIORouter.ts:84:14)
```

**Comment by grabs** [comment]
Hi Sven,

the cookie must not set as "httponly" because it is accessed via javascript. The "httponly" flag prevents such access.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Cookies#block_access_to_your_cookies

Best regards
Andreas

**Comment by slaudel** [comment]
> Hi Sven,
> 
> the cookie must not set as "httponly" because it is accessed via javascript. The "httponly" flag prevents such access. https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Cookies#block_access_to_your_cookies
> 
> Best regards Andreas

Hallo Andreas,

der Einfachheit halber schreibe ich jetzt auf Deutsch. Dass der Cookie nicht als "http_only" gesetzt sein soll, habe ich ja schon verstanden. Meine Frage ist, wie verhindere ich das? mod_etherpadlite setzt den Cookie anscheinend automatisch als "http_only".
In meinem "Hack" (siehe mein erster Post) habe ich in mod_etherpadlite das setzen des Cookies angepasst und explizit 
`'httponly' => false,` gesetzt. Leider ändert das nichts am Verhalten.
Wo kann ich noch drehen, dass der Cookie korrekt gesetzt wird?

Vielen Dank und viele Grüße
Sven

**Comment by grabs** [comment]
Hi Sven,

also mod_etherpadlite setzt den Cookie standardmäßig mit HttpOnly = false. Es wäre aber möglich, dass euer Webserver, also der von Moodle, das "HttpOnly" Flag hinzufügt. Dann kann Moodle bzw. das Plugin das nicht verhindern.
Was für einen Webserver nutzt ihr denn? Vielleicht habt ihr noch einen ReverseProxy davor, der die Header ebenfalls bearbeiten könnte.

Viele Grüße
Andreas

**Comment by slaudel** [comment]
Hallo Andreas,

wir haben das Problem lösen können. Es war in der Tat unser ReverseProxy/LoadBalancer, der noch eien Einstellung hatte, die alle Cookies als "http_only" ausgeliefert hat.

Danke für die Hinweise.
Viele Grüße
Sven
